version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: netlify-cms-app
    versions:
    - 2.14.26
    - 2.14.27
    - 2.14.29
    - 2.14.30
    - 2.14.32
    - 2.14.33
    - 2.14.35
    - 2.14.37
    - 2.14.38
    - 2.14.40
    - 2.14.43
    - 2.14.45
    - 2.14.46
  - dependency-name: flow-bin
    versions:
    - 0.146.0
    - 0.147.0
    - 0.148.0
    - 0.149.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.16
  - dependency-name: babel-preset-gatsby
    versions:
    - 1.0.0
    - 1.1.0
    - 1.2.0
    - 1.3.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: immer
    versions:
    - 8.0.1
    - 8.0.2
    - 8.0.3
  - dependency-name: gatsby
    versions:
    - 2.32.10
    - 2.32.11
